version: 2.1

executors:
  esp-bootstrap:
    docker:
      - image: esplinux/bootstrap
    working_directory: ~/
    environment:
      VERSION: "bootstrap"
      ESPBUILD_VERSION: "0.01"
      GHR_VERSION: "v0.12.1"

  build:
    executor: esp-bootstrap
    steps:
      - run: esp add ca-certificates zlib openssl curl espbuild ghr
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Build
          command: |
            mkdir -p ~/package
            build_index core $VERSION > ~/package/INDEX.txt
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/package

workflows:
  build:
    jobs:
      - build
