version: 2

jobs:
  build:
    docker:
      - image: esplinux/bootstrap
    working_directory: ~/
    environment:
      VERSION: "0.01"
    steps:
      - run:
          name: Build
          shell: /bin/sh -e
          command: |
            #esp add ca-certificates zlib openssl curl espbuild ghr
            tcurl -LO https://github.com/esplinux-core/zlib/releases/download/bootstrap/zlib-1.2.11.tar.gz
            tar xf zlib-1.2.11.tar.gz
            tcurl -LO https://github.com/esplinux-core/openssl/releases/download/bootstrap/openssl-1.1.1c.tar.gz
            tar xf openssl-1.1.1c.tar.gz
            tcurl -LO https://github.com/esplinux-core/curl/releases/download/bootstrap/curl-7.65.1.tar.gz
            tar xf curl-7.65.1.tar.gz
            tcurl -LO https://github.com/esplinux-core/espbuild/releases/download/bootstrap/espbuild-0.00.tar.gz
            tar xf espbuild-0.00.tar.gz
            tcurl -LO https://github.com/esplinux-core/ghr/releases/download/bootstrap/ghr-0.12.1.tar.gz
            tar xf ghr-0.12.1.tar.gz
            mkdir -p ~/package
            /bin/sh -x /bin/build_index core $VERSION > ~/package/INDEX.txt
            cat ~/package/INDEX.txt
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/package
